// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xokfcvcgitqoloqxmbrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhva2ZjdmNnaXRxb2xvcXhtYnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDc5NTgsImV4cCI6MjA2MzMyMzk1OH0.9AVonjSQTitQkaVW1SH939Dv7iv2T4xPNyRYEuo7cvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);